#!/usr/bin/env bash

# Variables
funcpath="$(pwd)/functions"

# Import functions
. "${funcpath}/test.func"

case "$1" in
  dump)
      . "${funcpath}/asdump.func"
      [ -z "$2" ] && aspkg_error_dump
      asdump "$2"
      ;;
  update)
      . "${funcpath}/cupdate.func"
      [ -z "$2" ] && aspkg_error_dump
      [ "$2" = git ] && cupgit
      [ "$2" = chroot ] && cupchroot
      ;;
  chroot)
      . "${funcpath}/chroot.func"
      [ "$2" = build ] && build
      ;;
  *)
      echo "Nothing provided"
esac


